#!/bin/bash

# Build directories
mkdir -p build
mkdir -p rom
mkdir -p music
mkdir -p psg

if [ -z "${1}" ]; then 
    echo "No arguments provided"
elif [ $1 == "build" ]; then
    docker build -t gba-builder .
    docker run --mount type=bind,src=.,dst=/app gba-builder
elif [ $1 == "clean" ]; then
    rm -r build/ rom/ music/ psg/
fi
